### ISSUE TITLE
Include git recipe

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/cookbook-lamp-server#3]
Noticed this was missing when I tried to do a test deploy with capistrano. Is this a good place to include it? @krues8dr

**Comment by krusynth** [comment]
After reflecting on this for a bit, I think we need a base-server of some sort for everything to extend.  That'll make it easier for us to stand up non-lamp boxes.

**Comment by sethetter** [comment]
Closing since the [base server](https://github.com/opengovfoundation/cookbook-base-server) cookbook exists now.
