### ISSUE TITLE
Dependency issue with libmysqlclient18

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/cookbook-lamp-server#4]
The [chef PHP cookbook](https://github.com/chef-cookbooks/php) has [as issue with the mysql client package version lock](https://github.com/chef-cookbooks/php/issues/154). This is causing problems for us when we include the MariaDB package.

Looks like the first time through, installation works. But after running it again, it will blow up when trying to install a lower version of `libmysql18` from the PHP cookbooks (which run first).

**Comment by sethetter** [comment]
@krues8dr attempted to [fork the php cookbook repo and remove the version lock on the mysql cookbook](https://github.com/opengovfoundation/cookbook-php).

Trying to run updated cookbooks on half-provisioned server (after previous failure) results in the same error.

First run through on a fresh box failed because of `make` missing. Have not investigated yet.

**Comment by krusynth** [comment]
This should be fixed with eb5a679e57a975813118ae2f8f91465e9eca7fbf but I'm still having a few problems with dependencies on CentOS here.  Will update once I figure that out.

**Comment by sethetter** [comment]
@krues8dr it's working for you on Ubuntu though? I'm still having issues it seems.
