### ISSUE TITLE
Handle apache template based on apache version

### ISSUE THREAD

**Issue by sethetter** [opengovfoundation/cookbook-lamp-server#7]
In Apache 2.2..

```
Order allow, deny
Allow from all
```

is replace by

```
Require all granted
```

In 2.4. Our template needs to handle this difference somehow. Or if we are certain that apache 2.4 will be installed (it is on Ubuntu with the current cookbooks, have not confirmed on others), then we can just go with the latter.

**Comment by krusynth** [comment]
Best to install `mod_version` to handle this probably.  

http://stackoverflow.com/questions/10707186/detect-apache-version-in-apache-config

**Comment by krusynth** [comment]
`IfDefine` is another option.
